### PR TITLE
v1.12.10 release: image tag workaround

### PR DESCRIPTION
**Pull request by thorn3r**

### CODE REVIEW

**Comment by michi-covalent** [comment]
suspicious build failure 👀

**Comment by thorn3r** [comment]
ya that is sus :eyes:

**Comment by thorn3r** [comment]
wonder if my branch name is throwing off the the build

**Comment by thorn3r** [comment]
i don't think the image build is actually supposed to run here, but my branch name tricked CI into doing it. closing this in favor of: https://github.com/isovalent/olm-for-cilium/pull/6 which passed CI

**Pull request closed without merging**
